apiVersion: v1
baseDomain: redhat.service.wekalab.io
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m5.4xlarge
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m5.xlarge
  replicas: 1
metadata:
  creationTimestamp: null
  name: coreos
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: eu-west-1
publish: External
pullSecret: | 
  {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNGEwNDc3YmM1ZjFhNDRmODhjMTI5N2Y4YmY0ZTM1Nzc6VFFFOEEwU1U4RDZJWTFVT1g4T1c2OTVDOVdaN1VSOFJMRjhRQkhaUTdVNzBTR1ZLR1A2QklOQkFEMTI3MU5EUA==","email":"ori@weka.io"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNGEwNDc3YmM1ZjFhNDRmODhjMTI5N2Y4YmY0ZTM1Nzc6VFFFOEEwU1U4RDZJWTFVT1g4T1c2OTVDOVdaN1VSOFJMRjhRQkhaUTdVNzBTR1ZLR1A2QklOQkFEMTI3MU5EUA==","email":"ori@weka.io"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTUzZTEzMTk4LTNiYTktNGM1Ni1iNGNiLWYyNTdkMjVlOGRmNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpNVE15TW1KbE1HRTVaV00wTkRRek9HWTNZVE0yTURoak1UVmxOV0prT0NKOS5XWWY4ZUFtOHJVb3BJM3R3b3RhV1hXVndNWkxkWC1keHFYY0NnejkwX2VqNlYxUTE0cWszdk9LRkFsOHdyLUtvSXdvUEtmV1B2UGlRRlc1Ukl0R2oxLVV5QVZUVkdkSW1iTHk3bjZnclhYUXRsc0xlMmZwUVdLNFk3WlNYcHJtemZhUUE1QzI1a1pseFdMVlhyeWhuVmhMYkZQbThEMmZ4VWhoN1Q1ajV3ZE9jTHExM0lId1hHR2ViQnJNNFl0eG1MLTBZVnNXc3E2VjlYVUp0MWdCYUJQcGE2WU9NaThOXzBHOUdmeVRIbVRvYzcyenBRR2dRX3FWR1BRSFRtbkJGR2NYWmN3VmtCR2I0ZTM1a1prbTA1Y3VMdll0cmg1WU9UaVNwM0lodU9tY3VpUjRkaFpYNmZzcTYxcDlOak44TTRKUVB3X25Kbml3aGw4NXhXOHRqN01TblNxaGp0bjVXa254RmtJYk1GOEplS1dzcjY3N3U4cV9oT180cEQtSGN1WFZJMGdvb3BhNHZVX3JZUFF5NHNsWTJfcnIyNTFKUGZWcEg5VDRReW9PNzlYYWlicWxyT2djS0Vka0tWX1NWMmZuTGdUWDFyME41N2pVOTJmdGlOTFhGb05tV2gzTlRwZHlrRHZ3UWgtUVk3bkN1TloxT21DLS1WX0lDb3Fya0g3aVc2Q0FodWtLVndTakRPRHRmS1dTMnhGRVEtTzVqVWFYOFRiNk51MUdjODZ2WER6a3o2TEFpSklkcDdqVC1lX1FtRVh4WDA3QkRXWWluVE83b056cDVyVDRvdTRkUU9HNl95UVdsWFlfQ2Vwam82Zkc2WnFFNG85NkxoeWJpVjV2N2FUWVBBczJCZWVqdnV1QzhvZmdmeXE3U2p2M2JKYXg1Mnc5YUV5WQ==","email":"ori@weka.io"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTUzZTEzMTk4LTNiYTktNGM1Ni1iNGNiLWYyNTdkMjVlOGRmNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpNVE15TW1KbE1HRTVaV00wTkRRek9HWTNZVE0yTURoak1UVmxOV0prT0NKOS5XWWY4ZUFtOHJVb3BJM3R3b3RhV1hXVndNWkxkWC1keHFYY0NnejkwX2VqNlYxUTE0cWszdk9LRkFsOHdyLUtvSXdvUEtmV1B2UGlRRlc1Ukl0R2oxLVV5QVZUVkdkSW1iTHk3bjZnclhYUXRsc0xlMmZwUVdLNFk3WlNYcHJtemZhUUE1QzI1a1pseFdMVlhyeWhuVmhMYkZQbThEMmZ4VWhoN1Q1ajV3ZE9jTHExM0lId1hHR2ViQnJNNFl0eG1MLTBZVnNXc3E2VjlYVUp0MWdCYUJQcGE2WU9NaThOXzBHOUdmeVRIbVRvYzcyenBRR2dRX3FWR1BRSFRtbkJGR2NYWmN3VmtCR2I0ZTM1a1prbTA1Y3VMdll0cmg1WU9UaVNwM0lodU9tY3VpUjRkaFpYNmZzcTYxcDlOak44TTRKUVB3X25Kbml3aGw4NXhXOHRqN01TblNxaGp0bjVXa254RmtJYk1GOEplS1dzcjY3N3U4cV9oT180cEQtSGN1WFZJMGdvb3BhNHZVX3JZUFF5NHNsWTJfcnIyNTFKUGZWcEg5VDRReW9PNzlYYWlicWxyT2djS0Vka0tWX1NWMmZuTGdUWDFyME41N2pVOTJmdGlOTFhGb05tV2gzTlRwZHlrRHZ3UWgtUVk3bkN1TloxT21DLS1WX0lDb3Fya0g3aVc2Q0FodWtLVndTakRPRHRmS1dTMnhGRVEtTzVqVWFYOFRiNk51MUdjODZ2WER6a3o2TEFpSklkcDdqVC1lX1FtRVh4WDA3QkRXWWluVE83b056cDVyVDRvdTRkUU9HNl95UVdsWFlfQ2Vwam82Zkc2WnFFNG85NkxoeWJpVjV2N2FUWVBBczJCZWVqdnV1QzhvZmdmeXE3U2p2M2JKYXg1Mnc5YUV5WQ==","email":"ori@weka.io"}}}
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC83xywjfh32vOUZGc2cWMBI7s0krK1au2EkWSTLkkOnsW7QVulrwqT5yi+02lVsJ7TPIV0DYTyg2GjkcUoBOyTu0/Msly9cTPv033SD+17CY3WAG29kY0OGkxSugpEWp4Z+vaQqGWP0G3D7yxBXQ0m0W3yDzNV+Jk3PERh4t7VU4T+zRmGy1cBttW1nQH9BewqgNfynQvUr3/YBkQXP0g2yTWtFM+0BUv4imcNpgm4/MQyQX41PJt0ey8v/pEuz9Hl75aZINwkdbQvSVWO2pcwwtkMtSK/89kYKCI3bF0gBSUPlnoPZorYyk+Y99nrOLUhSdrC8IjZ2DLQfzuwLNtl
  
