apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-perf
  name: worker-perf
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,worker-perf]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-perf: ""

